#! /usr/bin/env node
import { join, resolve } from 'node:path';
import { parseConfigFileTextToJson } from 'typescript';
import {
  copyFileSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { stdout } from 'node:process';

// Get outDir from tsConfig
export function getOutDir() {
  const tsConfigPath = resolve(process.cwd(), 'tsconfig.json');
  const tsConfigContent = readFileSync(tsConfigPath, 'utf-8');

  const config = parseConfigFileTextToJson(
    tsConfigPath,
    tsConfigContent,
  ).config;

  return config?.compilerOptions?.outDir ?? null;
}

// Remove out Dir with its contents
export function cleanOutDir(outDir) {
  const resolvedOutDir = resolve(process.cwd(), outDir);

  rmSync(resolvedOutDir, { recursive: true, force: true });
  mkdirSync(resolvedOutDir, { recursive: true });
}

// Copy the essential project files that aren't generated by the typescript compiler. These are LICENSE and README.md
export function copyEssentials(outDir, filesToCopy) {
  const resolvedOutDir = resolve(process.cwd(), outDir);

  for (const copyFile of filesToCopy) {
    stdout.write(`  - Copying ${copyFile} to '${outDir}'\n`);
    copyFileSync(copyFile, join(resolvedOutDir, copyFile));
  }
}

// Sanitize the package.json, remove devdependencies and scripts
export function cleanPackageJson() {
  const pkgPath = resolve(process.cwd(), 'package.json');
  const packageJson = JSON.parse(readFileSync(pkgPath, 'utf-8'));

  const keysToRemove = ['devDependencies', 'scripts'];
  keysToRemove.forEach((key) => {
    stdout.write(`  - Removing ${key} from package.json\n`);
    delete packageJson[key];
  });

  // Fix bin to be an object
  if (packageJson.bin && typeof packageJson.bin === 'string') {
    stdout.write(`  - Converting bin to object\n`);
    packageJson.bin = { [packageJson.name]: packageJson.bin };
  }

  return packageJson;
}

// Copy package.json to the out directory
export function copyPackageJson(outDir, packageJson) {
  const resolvedOutDir = resolve(process.cwd(), outDir);

  writeFileSync(
    join(resolvedOutDir, 'package.json'),
    JSON.stringify(packageJson, null, 2),
  );
}
